### ISSUE TITLE
Alacritty background doesn't match neovim

### ISSUE THREAD

**Issue by a-barjo** [Biscuit-Colorscheme/alacritty#1]
![image](https://github.com/Biscuit-Theme/alacritty/assets/47948089/ad4faa2d-ac4e-45a3-a1c5-9cde38030428)

Hello, I'm trying out the Biscuit theme with neovim and alacritty and enjoying the look of it so far. However what I've noticed is that the alacritty background doesn't match the neovim one as shown in the image above, the pane on the right has a slightly darker brown. Is this intentional?

**Comment by ghost** [comment]
no, it is not intentional! the neovim port hasn't been updated to use the new colorscheme yet

and, also, the alacritty port uses 10% lightened usual colors (steel blue, moss green, etc) for the lightened colors and has been also set as the default for other terminal ports (kitty, as an example for that)

the same person that has updated the alacritty port said that they would update the neovim port, from what i remember

**Comment by abb3v** [comment]
@adambarjo, Biscuit is undergoing developmental changes as of now, with adaptations to it's colorscheme, for now you may notice irregularities.
